### ISSUE TITLE
Proof-of-concept realtime Factorio rendering

### ISSUE THREAD

**Issue by Dimava** [FUE5BASE/FUE5#1]
If you configure Exporter mod to write to stdout the current serialized state of a chunk player is on every second, and configure FUE5 to use this data to regulary update entity states, you can make FUE5 act as an actual game renderer

**Comment by Atria1234** [comment]
We thought about that but it would require very large rewrites of parsing code so in the end we decided for FUE to be a once time export/import instead of continuous updates. If we decide to implement FUE as a running game renderer there are much more effective ways of actually doing it and all of them all quite hard to do.
