### ISSUE TITLE
Why not use nanite instead of LODs?

### ISSUE THREAD

**Issue by FluffyDiscord** [FUE5BASE/FUE5#2]
Title

**Comment by CorbinMeier** [comment]
It's been a while since I have used Nanite from Unreal Engine 5 (I tested it out when it came out), but if I recall, not all meshed are Nanite compatible unless set up that way. Please check out [this page](https://www.blendernation.com/2021/06/20/nanite-meshes-with-substance-painter-and-blender/) for more information.

The [FUE5 Discord](https://discord.gg/5dWyyH5wcU) does have a section in their current [TODOS](https://discord.com/channels/1072428808554172467/1072446571452575904): "figure out LOD/Nanite automation and provide test results".

Everyone that 3D models would need access to these tools and would need to make the meshes Nanite compatible.

Hope this helps.
